---
apiVersion: v1
kind: Secret
metadata:
  name: ryanj23-ryanj23-poi-map-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Summit23Janus2/ryanj23-frontend-gitops
